---
- include: variable-check.yml
  vars:
    playbook: rollback.yml

- name: Rollback a Deploy
  hosts: web:&{{ env }}
  remote_user: "{{ web_user }}"

  vars:
    project_root: "{{ www_root }}/{{ site }}"

  roles:
    - rollback
