---
- include: variable-check.yml
  vars:
    playbook: server.yml

- name: Determine Remote User
  hosts: web:&{{ env }}
  gather_facts: false
  roles:
    - { role: remote-user, tags: [remote-user, always] }

- name: Grav Server - Install LEMP Stack with PHP 7.0
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: common, tags: [common] }
    - { role: swapfile, swapfile_size: 1GB, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: ssmtp, tags: [ssmtp, mail] }
    - { role: php, tags: [php] }
    - { role: memcached, tags: [memcached] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: composer, tags: [composer] }
    - { role: letsencrypt, tags: [letsencrypt], when: letsencrypt_enabled }
    - { role: grav-setup, tags: [grav, grav-setup, letsencrypt] }
