---
- include: self-signed-certificate.yml
  tags: grav-setup-self-signed-certificate

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ grav_sites }}"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ grav_sites }}"

- include: nginx.yml
  tags: grav-setup-nginx
